### ISSUE TITLE
[Suggestion] More streamline CSS dev on the client

### ISSUE THREAD

**Issue by DebuUsagi** [Jiiks/BetterDiscordApp#119]
It's hard to dev discord css with the current way it's doing it. How about popping out the css editor to or go to the side of the app for more streamline editing?

Also, by default, custom css editor is empty. This should have the current css being used already in the editor. And/or a drop down of the different modes BetterDiscordApp offers.

Lastly, how do you even find elements on this app? Do we load discord in the browser and start figuring out which elements do what and throw them in the css editor?

**Comment by DebuUsagi** [comment]
Also, I can't change css that have the !important tag on it

help

**Comment by DoNotSpamPls** [comment]
I think the styles with "!important" are essential for the proper work of Discord

**Comment by DebuUsagi** [comment]
@DoNotSpamPls  Not all of them are essential, for example:
.twitchcord-button-open {
	background-image:url(https://static-cdn.jtvnw.net/emoticons/v1/354/1.0) !important;
}

The image is just 4Head, but with the !important tag there, I can't change the image to anything else *through the use of the css editor on the app*. Which is the part I find terrible.

**Comment by pohky** [comment]
you should be able to change everything, even the !important ones, by adding !important yourself
worked just fine with the example you gave there.
also finding things is the same in the app and the browser, spress ctrl+shift+i and deattach it from the window then click the little magnifying glass in the top left corner then click the element of interest

but i agree the little custom css box isn't very helpfull

**Comment by DebuUsagi** [comment]
@pohky ![disc](https://dl.dropboxusercontent.com/u/123314639/discwa4.jpg)

Am I using the wrong element here, or?

Also, do you know the element for ![channelheader](https://dl.dropboxusercontent.com/u/123314639/discwa5.jpg)
The element found in the browser version doesn't seem to change it, or I've missed it entirely.

Lastly, if I wanted to add elements so I can do some more fun stuff, how would I get around to doing so?

**Comment by pohky** [comment]
didn't know which one you meant so here are all element in there
```css
.guild-channels ul .channel {
    background-color: darkgreen;
}
.guild-channels ul .channel-text.selected a {
    background-color: yellow;
}
.guild-channels ul .channel-text .channel-name {
    color: red;
    background-color: black;
}
.guild-channels ul .channel-text.selected:before {
    border-left: 4px solid red;
}
.guild-channels ul .channel-text .channel-name:before {
    color: blue!important;
}
```
you can also change the # symbol visualy with css by adding `content: 'something';` to the last one

all i use for changing the image on the emote button is
```css
#twitchcord-button {
    background-image: url(https://cdn.frankerfacez.com/emoticon/72267/1);
}
.twitchcord-button-open {
    background-image: url(https://cdn.frankerfacez.com/emoticon/72263/1)!important;
}
```
![closed](https://cloud.githubusercontent.com/assets/1510568/12081719/bcda7b12-b282-11e5-9fe0-a2cac356edc7.png) ![open](https://cloud.githubusercontent.com/assets/1510568/12081721/c9c8a312-b282-11e5-87dc-5c57199352b4.png)
