### ISSUE TITLE
Minimal mode width

### ISSUE THREAD

**Issue by tehbasshunter** [Jiiks/BetterDiscordApp#533]
The current width for minimal mode is too small and cuts off the buttons in the account area.  
  
The current code which is:
```CSS
.bd-minimal .channels-wrap { width: 160px;}
```
It should be this instead:
```CSS
.bd-minimal .channels-wrap { width: 230px;}
```  
  
This would effect [this](https://github.com/Jiiks/BetterDiscordApp/blob/master/css/main.css#L679).
