### ISSUE TITLE
Theme transparency randomly broke

### ISSUE THREAD

**Issue by TwilightVanish** [Jiiks/BetterDiscordApp#679]
All themes using transparency just broke an hour ago (for me at least). Everything is just black in the background and several transparent items are no longer transparent.

**Comment by GummiWummiBear** [comment]
I just installed BD on a different this morning and noticed this as well when messing around with the Custom CSS.

**Comment by dinosw** [comment]
It seems that a few names in the code was changed by Discord.  
BD's dark theme for the emojipicker isn't working either anymore.  
I also used to be able to change the height of the emojipicker using this:  
`.emojiPicker .scroller{ height: 450px; }`  
But now I have to do this instead:  
`.emojiPicker-3g68GS .scroller-2dsok0{ height: 450px; }`

**Comment by Inve1951** [comment]
```CSS
/* fix not having a background image anymore */
.layers-20RVFW, .layer-kosS71, .container-2OU7Cz, .typing-3eiiL_ {
  background: transparent !important;
}
/* optionally adjust background brightness (0: original image, 1: black) */
.layers-20RVFW {
  background: rgba(0,0,0, 0.3) !important;
}
```
