### ISSUE TITLE
theme error 

### ISSUE THREAD

**Issue by guiltyakaii** [Jiiks/BetterDiscordApp#761]
![image](https://user-images.githubusercontent.com/38133500/38422433-0cb9d1c6-39ab-11e8-9c84-f2306a98181d.png)

**Comment by Modder4869** [comment]
this is for BD related issues , not themes , either way update it or add this to custom css
```css
.members-1bid1J {
/*rgba(red,green,blue,alpha)*/
    background: rgba(0,0,0,0.6) !important;
}
```
change 0,6 to whatever that matches your theme
